# This Dockerfile creates a container that can be used for development
# of the libpostal-rest service. Just build this and then start a
# container by mapping your GOPATH folder into the container.
# You can also map the ports to some host ports to access a running
# service inside the container for testing.
FROM golang:1.18-bullseye

ARG COMMIT
ENV COMMIT ${COMMIT:-master}
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
    autoconf automake build-essential curl git libsnappy-dev libtool pkg-config

WORKDIR /
RUN git clone https://github.com/openvenues/libpostal -b $COMMIT

WORKDIR /libpostal

# Copy the commands from build_libpostal.sh here
# and execute them as a single RUN commnad.
# This reduces the number of layers in the Docker image
RUN ./bootstrap.sh \
  && mkdir -p /opt/libpostal_data \
  && ./configure --datadir=/opt/libpostal_data \
  && make -j4 \
  && make install \
  && ldconfig \
  && pkg-config --cflags libpostal

RUN useradd -m godev

CMD /bin/bash
